const DeviceTypes = {
  DEFAULT: 'DEFAULT', //+
  LAMP: 'LAMP', //+
  LOCK: 'LOCK', //+
  THERMOSTAT: 'THERMOSTAT',
  SHUTTER: 'SHUTTER',
  SIGNALIZATION: 'SIGNALIZATION',
  COOLER: 'COOLER',
  SOCKET: 'SOCKET', //+
  CAMERA: 'CAMERA',
  RING_BELL: 'RING_BELL',
  CONDITIONER: 'CONDITIONER',
  AIR_CLEANER: 'AIR_CLEANER',
  HUMIDIFIER: 'HUMIDIFIER',
  FRIDGE: 'FRIDGE',
  SENSOR:'SENSOR',
  STOVE: 'STOVE',
  TV: 'TV',
};

export default DeviceTypes;