const ActionTypes = {

  //MenuHeader Action Types
  SETTINGS_OPENED: 'SETTINGS_OPENED',
  HOMEBUTTON_CLICKED: 'HOMEBUTTON_CLICKED',

  //AppView Action Types
  SCENARIO_SELECTED: 'SCENARIO_SELECTED',
  ROOM_SELECTED: 'ROOM_SELECTED',
  DEVICE_SELECTED: 'DEVICE_SELECTED',
  VIEWALL_CLICKED: 'VIEWALL_CLICKED',
  ADD_BUTTON_CLICKED: 'ADD_BUTTON_CLICKED',
  NEW_ROOM_ADDED: 'NEW_ROOM_ADDED',
  NEW_DEVICE_ADDED: 'NEW_DEVICE_ADDED',

  //RoomView Action Types
  // SCENARIO_SELECTED
  // DEVICE_SELECTED
  // ADD_BUTTON_CLICKED
  TRYING_TO_ADD_DEVICE_TO_ROOM: 'TRYING_TO_ADD_DEVICE_TO_ROOM',
  DEVICE_ADDED_TO_ROOM: 'DEVICE_ADDED_TO_ROOM',
  ROOM_SETTINGS_CHANGED: 'ROOM_SETTINGS_CHANGED',
  ROOM_DELETED: 'ROOM_DELETED',
};

export default ActionTypes;