const ActionTypes = {

  //MainMenu Action Types
  SETTINGS_OPENED: 'SETTINGS_OPENED',
  SCENARIO_SELECTED: 'SCENARIO_SELECTED',
  ROOM_SELECTED: 'ROOM_SELECTED',
  DEVICE_SELECTED: 'DEVICE_SELECTED',
  VIEWALL_SWITCHED: 'VIEWALL_SWITCHED',
  VIEWMORE_SELECTED: 'VIEWMORE_SELECTED',
  ADD_BUTTON_CLICKED: 'ADD_BUTTON_CLICKED',

  NEW_DEVICE_ADDED: 'NEW_DEVICE_ADDED',
  NEW_ROOM_ADDED: 'NEW_ROOM_ADDED',
  ROOM_SETTINGS_CHANGED: 'ROOM_SETTINGS_CHANGED',
  ROOM_DELETED: 'ROOM_DELETED',
};

export default ActionTypes;